databases:
- engine: PG
  name: guildso-db
  num_nodes: 1
  size: db-s-dev-database
  version: "12"
name: guildso
region: ams
services:
- environment_slug: php
  run_command: heroku-php-apache2 public/
  envs:
  - key: APP_NAME
    scope: RUN_TIME
    value:  Guild
  - key: APP_ENV
    scope: RUN_TIME
    value: dev
  - key: APP_KEY
    scope: RUN_TIME
    value: base64:UdAH2B63rlotjrkSSsj3Hppy4gbfr+OeHvtSdF9r9q8=
  - key: APP_DEBUG
    scope: RUN_TIME
    value: "1"
  - key: APP_URL
    scope: RUN_TIME
    value: ${APP_URL}
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${guildso-db.DATABASE_URL}
  - key: DB_CONNECTION
    scope: RUN_TIME
    value: pgsql
  - key: DB_HOST
    scope: RUN_TIME
    value: ${guildso-db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${guildso-db.PORT}
  - key: DB_DATABASE
    scope: RUN_TIME
    value: ${guildso-db.DATABASE}
  - key: DB_USERNAME
    scope: RUN_TIME
    value: ${guildso-db.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_TIME
    value: ${guildso-db.PASSWORD}
  github:
    branch: main
    deploy_on_push: true
    repo: guildso/guild
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xs
  name: landing-laravel
  routes:
  - path: /
jobs:
- name: migrate
  kind: POST_DEPLOY
  github:
    repo: guildso/guild
    branch: main
    deploy_on_push: true
  run_command: php artisan migrate --seed
  envs:
  - key: APP_NAME
    scope: RUN_TIME
    value:  Guild
  - key: APP_ENV
    scope: RUN_TIME
    value: dev
  - key: APP_KEY
    scope: RUN_TIME
    value: base64:UdAH2B63rlotjrkSSsj3Hppy4gbfr+OeHvtSdF9r9q8=
  - key: APP_DEBUG
    scope: RUN_TIME
    value: "1"
  - key: APP_URL
    scope: RUN_TIME
    value: ${APP_URL}
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${guildso-db.DATABASE_URL}
  - key: DB_CONNECTION
    scope: RUN_TIME
    value: pgsql
  - key: DB_HOST
    scope: RUN_TIME
    value: ${guildso-db.HOSTNAME}
  - key: DB_PORT
    scope: RUN_TIME
    value: ${guildso-db.PORT}
  - key: DB_DATABASE
    scope: RUN_TIME
    value: ${guildso-db.DATABASE}
  - key: DB_USERNAME
    scope: RUN_TIME
    value: ${guildso-db.USERNAME}
  - key: DB_PASSWORD
    scope: RUN_TIME
    value: ${guildso-db.PASSWORD}